### ISSUE TITLE
Can't display / load the plugins directory

### ISSUE THREAD

**Issue by ThomasFis** [JustFxDev/Portable-Kanboard-and-Webserver#2]
My plugins Directory list (which should be fetched from 'https://kanboard.org/plugins.json') is always empty.
Ist this a general issue or do I have this only in my installation?

**Comment by ThomasFis** [comment]
Have now seen that this is a general issue with this type of installation

error.log shows
[Tue Feb 21 15:57:57.042238 2023] [php:notice] [pid 20384:tid 1272] [client ::1:54637] [error] HttpClient: request failed (https://kanboard.org/plugins.json - SSL certificate problem: unable to get local issuer certificate)

The localhost instance misses the needed certificates.

Steps to solve:
a) download cacert.pem from https://curl.se/docs/caextract.html -> this is the Mozilla CA certificate store in PEM format
b) copy the cacert.pem to a directory - I have used the php directory inside the usbwebserver tree
c) Add the following configuration to php.ini: curl.cainfo=”C:\Installation_Dir\php\cacert.pem”
-> absolute path to the cacert.pem file
d) restart the server and it should work now

**Comment by JustFxDev** [comment]
Hi ThomasFis,

thanks for your support! I added your fix for this to the latest release (v1.0.1). But i changed not the `.\php\ php.ini`, because this will be overwritten on each startup with the file `\settings\php.ini`

Also the `{path}` variable has to be used to keep it portable (see `curl.cainfo` in `\settings\php.ini` . That's the reason for overwriting the orginal ini files. Just to mention.

Thanks again!

Cheers, Fx
